### ISSUE TITLE
Can you list the hardware you used to train this?

### ISSUE THREAD

**Issue by aadimator** [maciej-sypetkowski/autoascend#3]
I'd really appreciate it if you could mention the hardware you used to compete. This would give me an idea if an independent researcher can hope to do something in this area or is it mostly like LLMs, exclusively for large companies with huge amount of compute.

**Comment by msypetkowski** [comment]
Just 2 moderately good CPUs -- one PC 8-core 11-gen (in this time it was the latest) and one older PC intel CPU  with 12 cores. So basically you could do that on a laptop with not too bad CPU, but it could be more convenient to have more cores, because measuring improvement takes longer and longer (the better the agent is).

**Comment by aadimator** [comment]
Many thanks for the quick response.
